# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a2178149d3f0f60a815c85430a0c627b"
name = "unthink-aura-connect"
handle = "unthink-aura-connect"
application_url = "https://letter-definitely-popularity-establish.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "aura-test-connect.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://letter-definitely-popularity-establish.trycloudflare.com/auth/callback",
  "https://letter-definitely-popularity-establish.trycloudflare.com/auth/shopify/callback",
  "https://letter-definitely-popularity-establish.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
